name: themarip_backend
description: Themar backend server
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_jsonwebtoken: ^2.7.1
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  shelf_cors_headers: ^0.1.5
  dotenv: ^4.0.1
  postgres: ^2.5.4

dev_dependencies:
  test: any
